service: graphql-api

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:CreateTable
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

functions:
  query:
    handler: handler.query
    events:
      - http:
          path: query
          method: get
          cors: true
  createTable:
    handler: handler.query
    events:
      - http:
          path: createTable
          method: get
          cors: true
  hello:
    handler: handler2.hello
    events:
      - http:
          path: test
          method: get
          cors: true